// Assets+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written Assets.swift.

import FOSFoundation
import Foundation

extension Assets {
    /// Tether, CoinGecko's `tether`: its home on EIP155.Ethereum, then its other instances
    public static let tether: AssetDeclaration = try! AssetDeclaration(
        asset: Asset(validating: EIP155.Ethereum.tether.instance.id),
        tokenName: "Tether",
        symbol: AssetSymbol(validating: "USDT"),
        aggregatorId: "tether",
        instances: [
            EIP155.Ethereum.tether,
            EIP155.Avalanche.tether,
            EIP155.Celo.tether,
            TRON.Tron.tether,
            SOLANA.Solana.tether,
            NEAR.Near.tether
        ]
    )

    /// USDC, CoinGecko's `usd-coin`: its home on EIP155.Ethereum, then its other instances
    public static let usdCoin: AssetDeclaration = try! AssetDeclaration(
        asset: Asset(validating: EIP155.Ethereum.usdCoin.instance.id),
        tokenName: "USDC",
        symbol: AssetSymbol(validating: "USDC"),
        aggregatorId: "usd-coin",
        instances: [
            EIP155.Ethereum.usdCoin,
            EIP155.Polygon.usdCoin,
            EIP155.Optimism.usdCoin,
            EIP155.Avalanche.usdCoin,
            EIP155.Celo.usdCoin,
            EIP155.Base.usdCoin,
            TRON.Tron.usdCoin,
            SOLANA.Solana.usdCoin,
            XRPL.XRPLedger.usdCoin,
            STELLAR.Stellar.usdCoin,
            ALGORAND.Algorand.usdCoin,
            HEDERA.Hedera.usdCoin,
            NEAR.Near.usdCoin
        ]
    )

    /// Pepe, CoinGecko's `pepe`: its home on EIP155.Ethereum, then its other instances
    public static let pepe: AssetDeclaration = try! AssetDeclaration(
        asset: Asset(validating: EIP155.Ethereum.pepe.instance.id),
        tokenName: "Pepe",
        symbol: AssetSymbol(validating: "PEPE"),
        aggregatorId: "pepe",
        instances: [
            EIP155.Ethereum.pepe,
            EIP155.BinanceSmartChain.pepe,
            EIP155.Avalanche.pepe
        ]
    )

    /// Every declaration above, in this file's order: what `AssetRegistry.shared` holds from the start
    public static let all: [AssetDeclaration] = [
        tether,
        usdCoin,
        pepe
    ]
}
