// EIP155+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written EIP155.swift.

import FOSFoundation
import Foundation

extension EIP155.Ethereum {
    /// Tether, CoinGecko's `tether`, at 6 decimals
    public static let tether: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0xdac17f958d2ee523a2206206994597c13d831ec7"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDT")
    )

    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )

    /// Pepe, CoinGecko's `pepe`, at 18 decimals
    public static let pepe: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0x6982508145454ce325ddbe47a25d4ec3d2311933"),
        decimals: 18,
        symbol: AssetSymbol(validating: "PEPE")
    )
}

extension EIP155.BinanceSmartChain {
    /// Pepe, CoinGecko's `pepe`, at 18 decimals
    public static let pepe: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0x25d887ce7a35172c62febfd67a1856f20faebb00"),
        decimals: 18,
        symbol: AssetSymbol(validating: "PEPE")
    )
}

extension EIP155.Polygon {
    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )
}

extension EIP155.Optimism {
    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0x0b2c639c533813f4aa9d7837caf62653d097ff85"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )
}

extension EIP155.Fantom {
}

extension EIP155.Avalanche {
    /// Tether, CoinGecko's `tether`, at 6 decimals
    public static let tether: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0x9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDT")
    )

    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )

    /// Pepe, CoinGecko's `pepe`, at 18 decimals
    public static let pepe: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0xa659d083b677d6bffe1cb704e1473b896727be6d"),
        decimals: 18,
        symbol: AssetSymbol(validating: "PEPE")
    )
}

extension EIP155.EthereumClassic {
}

extension EIP155.Celo {
    /// Tether, CoinGecko's `tether`, at 6 decimals
    public static let tether: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0x48065fbbe25f71c9282ddf5e1cd6d6a887483d5e"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDT")
    )

    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0xceba9300f2b948710d2653dd7b07f33a8b32118c"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )
}

extension EIP155.Base {
    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )
}

extension EIP155.Theta {
}

extension EIP155.COTI {
}
