// STELLAR+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written STELLAR.swift.

import FOSFoundation
import Foundation

extension STELLAR.Stellar {
    /// USDC, CoinGecko's `usd-coin`, at 7 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75"),
        decimals: 7,
        symbol: AssetSymbol(validating: "USDC")
    )
}
