// TRON+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written TRON.swift.

import FOSFoundation
import Foundation

extension TRON.Tron {
    /// Tether, CoinGecko's `tether`, at 6 decimals
    public static let tether: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDT")
    )

    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )
}
