// BinanceExchangeChain+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from Binance's exchange information and CoinGecko's tickers on 2026-10-07; do not edit; hand additions go in BinanceExchangeChain+Overrides.swift.

import struct CryptoAsset.Asset
import struct CryptoAsset.AssetDeclaration
import enum CryptoAsset.Assets
import enum CryptoAsset.BIP122
import enum CryptoAsset.EIP155
import enum CryptoAsset.TRON

extension BinanceExchangeChain {
    /// The rows generated from Binance's exchange information and CoinGecko's tickers: each holding keyed by the
    /// first of its wire names, its class `nil` where the importer generated none
    static let importedRows: [Row] = [
        // BTC: CoinGecko's `bitcoin`
        Row(holding: BinanceHolding(address: "BTC"), wireNames: ["BTC"], decimals: 8, symbol: "BTC", asset: try! Asset(validating: BIP122.Bitcoin.btc.instance.id)),
        // USDT: CoinGecko's `tether`
        Row(holding: BinanceHolding(address: "USDT"), wireNames: ["USDT"], decimals: 8, symbol: "USDT", asset: Assets.tether.asset),
    ]
}
