// KrakenExchangeChain+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from Kraken's Assets answer and CoinGecko's tickers on 2026-10-07; do not edit; hand additions go in KrakenExchangeChain+Overrides.swift.

import struct CryptoAsset.Asset
import struct CryptoAsset.AssetDeclaration
import enum CryptoAsset.Assets
import enum CryptoAsset.BIP122
import enum CryptoAsset.EIP155
import enum CryptoAsset.SOLANA
import enum CryptoAsset.TRON

extension KrakenExchangeChain {
    /// The rows generated from Kraken's Assets answer and CoinGecko's tickers: each holding keyed by the
    /// first of its wire names, its class `nil` where the importer generated none
    static let importedRows: [Row] = [
        // SOL: CoinGecko's `solana`
        Row(holding: KrakenHolding(address: "SOL"), wireNames: ["SOL"], decimals: 10, symbol: "SOL", asset: try! Asset(validating: SOLANA.Solana.sol.instance.id)),
        // ETH: CoinGecko's `ethereum`
        Row(holding: KrakenHolding(address: "ETH"), wireNames: ["ETH", "XETH"], decimals: 10, symbol: "ETH", asset: try! Asset(validating: EIP155.Ethereum.eth.instance.id)),
        // XBT: CoinGecko's `bitcoin`
        Row(holding: KrakenHolding(address: "XBT"), wireNames: ["XBT", "XXBT"], decimals: 10, symbol: "XBT", asset: try! Asset(validating: BIP122.Bitcoin.btc.instance.id)),
    ]
}
