// ALGORAND+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written ALGORAND.swift.

import FOSFoundation
import Foundation

extension ALGORAND.Algorand {
    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "31566704"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )

    /// Brazilian Digital, CoinGecko's `brz`, at 4 decimals
    public static let brz: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "112866019"),
        decimals: 4,
        symbol: AssetSymbol(validating: "BRZ")
    )

    /// FOLKS, CoinGecko's `folks`, at 6 decimals
    public static let folks: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "3203964481"),
        decimals: 6,
        symbol: AssetSymbol(validating: "FOLKS")
    )

    /// Realio Network Token, CoinGecko's `realio-network`, at 7 decimals
    public static let realioNetwork: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "2751733"),
        decimals: 7,
        symbol: AssetSymbol(validating: "RIO")
    )
}
