// BIP122+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written BIP122.swift.

import FOSFoundation
import Foundation

extension BIP122.Bitcoin {
}

extension BIP122.Litecoin {
}

extension BIP122.Dogecoin {
}

extension BIP122.BitcoinCash {
}

extension BIP122.Dash {
}

extension BIP122.DigiByte {
}

extension BIP122.Ravencoin {
}

extension BIP122.Zcash {
}

extension BIP122.Verge {
}

extension BIP122.Qtum {
}

extension BIP122.ECash {
}
