// COSMOS+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written COSMOS.swift.

import FOSFoundation
import Foundation

extension COSMOS.CosmosHub {
}

extension COSMOS.THORChain {
}

extension COSMOS.Terra {
}

extension COSMOS.FetchAI {
}
