// HEDERA+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written HEDERA.swift.

import FOSFoundation
import Foundation

extension HEDERA.Hedera {
    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0.0.456858"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )

    /// Chainlink, CoinGecko's `chainlink`, at 18 decimals
    public static let chainlink: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "0x7ce6bb2cc2d3fd45a974da6a0f29236cb9513a98"),
        decimals: 18,
        symbol: AssetSymbol(validating: "LINK")
    )
}
