// NEAR+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written NEAR.swift.

import FOSFoundation
import Foundation

extension NEAR.Near {
    /// Tether, CoinGecko's `tether`, at 6 decimals
    public static let tether: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "usdt.tether-token.near"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDT")
    )

    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )
}
