// XRPL+Imported.swift
//
// Copyright © 2026 FOS Services, LLC. All rights reserved.
//
// Generated by Scripts/import-assets.swift from CoinGecko on 2026-10-07; do not edit; hand additions go in the hand-written XRPL.swift.

import FOSFoundation
import Foundation

extension XRPL.XRPLedger {
    /// USDC, CoinGecko's `usd-coin`, at 6 decimals
    public static let usdCoin: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "5553444300000000000000000000000000000000.rGm7WCVp9gb4jZHWTEtGUr4dd74z2XuWhE"),
        decimals: 6,
        symbol: AssetSymbol(validating: "USDC")
    )

    /// EUR CoinVertible, CoinGecko's `societe-generale-forge-eurcv`, at 0 decimals
    public static let societeGeneraleForgeEurcv: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "4555524356000000000000000000000000000000.rUNaS5sqRuxZz6V7rBGhoSaZiVYA3ut4UL"),
        decimals: 0,
        symbol: AssetSymbol(validating: "EURCV")
    )

    /// EURØP, CoinGecko's `schuman-europ`, at 0 decimals
    public static let schumanEurop: AssetDeclaration.Instance = try! AssetDeclaration.Instance(
        instance: AssetInstance(validating: chainId + ":" + "EUROP.rMkEuRii9w9uBMQDnWV5AA43gvYZR9JxVK"),
        decimals: 0,
        symbol: AssetSymbol(validating: "EUROP")
    )
}
