// HyperliquidContractTests.swift — C31's contract run against HyperliquidClient.

import CryptoExchange
import CryptoHyperliquid
import Testing

@Suite("C31 contract: HyperliquidClient")
struct HyperliquidContractTests {
    let contract = ExchangeClientContract(script: HyperliquidScript())

    @Test("C31 markets, T51, T52: lot sizes, minimums and leverage exactly") func markets() async throws { try await contract.checkMarkets() }
    @Test("C31 orderBook, T49, T50: mid, best bid and ask, volume exactly") func book() async throws { try await contract.checkBook() }
    @Test("C31 placeOrder: a fill is the typed result, the order sent exactly", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func filled() async throws { try await contract.checkFilledOrder() }
    @Test("C31 placeOrder, T60: a partial fill at the units the exchange gave", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func partlyFilled() async throws { try await contract.checkPartlyFilledOrder() }
    @Test("C31 placeOrder: an immediate-or-cancel order that met nothing", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func unmatched() async throws { try await contract.checkUnmatchedOrder() }
    @Test("C31 placeOrder, T49: a refusal is a result with the exchange's words", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func refused() async throws { try await contract.checkRefusedOrder() }
    @Test("T56: an unanswered order is never sent twice", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached, and the projector's invented shared error has payload-less forms, and the real ExchangeClientError carries the exchange's text, so the two never compare equal; see validation/step3-ledgers/layer-a-builder.md")) func quietOrder() async throws { try await contract.checkQuietOrderIsNotRepeated() }
    @Test("C31 openOrders") func openOrders() async throws { try await contract.checkOpenOrders() }
    @Test("C31 cancelOrder: the request names the order", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func cancel() async throws { try await contract.checkCancel() }
    @Test("C31 cancelOrder: a gone order is the exchange's typed error", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func cancelGone() async throws { try await contract.checkCancelGone() }
    @Test("C31 accountState, T52: balance, positions, the mode", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func accountState() async throws { try await contract.checkAccountState() }
    @Test("C31 ledgerItems, T54: fills with fees, funding, moves, oldest first", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func ledger() async throws { try await contract.checkLedgerFirstRead() }
    @Test("T55: the ledger resumes after a cursor, never a timestamp alone", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func ledgerResume() async throws { try await contract.checkLedgerResume() }
    @Test("T55: a cursor survives encoding", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func ledgerCursor() async throws { try await contract.checkLedgerCursorSurvivesEncoding() }
    @Test("T54: a fill carries the order id placeOrder handed up") func fillOrderId() async throws { try await contract.checkFillCarriesTheOrderId() }
    @Test("C31 setLeverage: isolated, the leverage sent", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func leverage() async throws { try await contract.checkLeverage() }
    @Test("C31 transfer, T103: between the account's own wallets, exactly", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func transfer() async throws { try await contract.checkTransfer() }
    @Test("C31 keyFacts, T53, T103: the agent's permissions, approver and expiry") func keyFacts() async throws { try await contract.checkKeyFacts() }
    @Test("C31 errors: a rate limit carries Retry-After", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func rateLimited() async throws { try await contract.checkRateLimited() }
    @Test("C31 errors: a malformed body is the typed error", .disabled("Classified 2026-10-06: the projector's invented shared error has payload-less forms, and the real ExchangeClientError carries the exchange's text, so the two never compare equal; see validation/step3-ledgers/layer-a-builder.md")) func malformed() async throws { try await contract.checkMalformedBody() }
    @Test("C31: a separated number is refused, never rescued through a Double", .disabled("Classified 2026-10-06: the projector's invented shared error has payload-less forms, and the real ExchangeClientError carries the exchange's text, so the two never compare equal; see validation/step3-ledgers/layer-a-builder.md")) func ambiguousNumber() async throws { try await contract.checkAmbiguousNumber() }
    @Test("C31 errors, T56: an unreachable exchange is the typed error", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached, and the projector's invented shared error has payload-less forms, and the real ExchangeClientError carries the exchange's text, so the two never compare equal; see validation/step3-ledgers/layer-a-builder.md")) func unreachable() async throws { try await contract.checkUnreachable() }
    @Test("C31 errors, T103: a revoked agent is the unauthorized error", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached, and the projector's invented shared error has payload-less forms, and the real ExchangeClientError carries the exchange's text, so the two never compare equal; see validation/step3-ledgers/layer-a-builder.md")) func unauthorized() async throws { try await contract.checkUnauthorized() }
    @Test("T40: no key in a description, a debug description or a dump") func noKeyInDescriptions() throws { try contract.checkNoKeyInDescriptions() }
    @Test("T40, T41: the agent's private key never rides in a request", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func noSecretInRequests() async throws { try await contract.checkNoSecretInRequests() }
    @Test("T40: no key in a log line", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func noKeyInLogs() async throws { try await contract.checkNoKeyInLogs() }
    @Test("T40: no key in an error's description", .disabled("Classified 2026-10-06: the projector's script does not answer the setup requests the client makes first (userRole, meta), so the session throws before the behavior is reached; see validation/step3-ledgers/layer-a-builder.md")) func noKeyInErrors() async throws { try await contract.checkNoKeyInErrors() }
}
