name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  run_tests:
    runs-on: macos-12
    env:
      ETHER_SCAN_KEY: ${{ secrets.ETHER_SCAN_KEY }}
      ETH_TEST_CONTRACT_ADDRESS: ${{ secrets.ETH_TEST_CONTRACT_ADDRESS }}

    steps:
     - uses: actions/checkout@v2

     - name: Run Tests
       run: swift test