name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  run_tests:
    runs-on: macos-12
    env:
      BTC_TEST_CONTRACT_ADDRESS: ${{ secrets.BTC_TEST_CONTRACT_ADDRESS }}
      ETHER_SCAN_KEY: ${{ secrets.ETHER_SCAN_KEY }}
      ETH_TEST_CONTRACT_ADDRESS: ${{ secrets.ETH_TEST_CONTRACT_ADDRESS }}
      FTM_SCAN_KEY: ${{ secrets.FTM_SCAN_KEY }}
      FTM_TEST_CONTRACT_ADDRESS: ${{ secrets.FTM_TEST_CONTRACT_ADDRESS }}
      BSC_SCAN_KEY: ${{ secrets.BSC_SCAN_KEY }}
      BSC_TEST_CONTRACT_ADDRESS: ${{ secrets.BSC_TEST_CONTRACT_ADDRESS }}
      POLYGON_SCAN_KEY: ${{ secrets.POLYGON_SCAN_KEY }}
      POLYGON_TEST_CONTRACT_ADDRESS: ${{ secrets.POLYGON_TEST_CONTRACT_ADDRESS }}
      OPTIMISTIC_ETHER_SCAN_KEY: ${{ secrets.OPTIMISTIC_ETHER_SCAN_KEY }}
      OPTIMISTIC_TEST_CONTRACT_ADDRESS: ${{ secrets.OPTIMISTIC_TEST_CONTRACT_ADDRESS }}

    steps:
     - uses: actions/checkout@v2

     - name: Run Tests
       run: swift test --enable-code-coverage

  analyze_code_coverage:
    runs-on: macos-12
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      BTC_TEST_CONTRACT_ADDRESS: ${{ secrets.BTC_TEST_CONTRACT_ADDRESS }}
      ETHER_SCAN_KEY: ${{ secrets.ETHER_SCAN_KEY }}
      ETH_TEST_CONTRACT_ADDRESS: ${{ secrets.ETH_TEST_CONTRACT_ADDRESS }}
      FTM_SCAN_KEY: ${{ secrets.FTM_SCAN_KEY }}
      FTM_TEST_CONTRACT_ADDRESS: ${{ secrets.FTM_TEST_CONTRACT_ADDRESS }}
      BSC_SCAN_KEY: ${{ secrets.BSC_SCAN_KEY }}
      BSC_TEST_CONTRACT_ADDRESS: ${{ secrets.BSC_TEST_CONTRACT_ADDRESS }}
      POLYGON_SCAN_KEY: ${{ secrets.POLYGON_SCAN_KEY }}
      POLYGON_TEST_CONTRACT_ADDRESS: ${{ secrets.POLYGON_TEST_CONTRACT_ADDRESS }}
      OPTIMISTIC_ETHER_SCAN_KEY: ${{ secrets.OPTIMISTIC_ETHER_SCAN_KEY }}
      OPTIMISTIC_TEST_CONTRACT_ADDRESS: ${{ secrets.OPTIMISTIC_TEST_CONTRACT_ADDRESS }}

    steps:
     - uses: actions/checkout@v2

     - name: Generate an xcodeproj
       run: swift package generate-xcodeproj

     - name: Run Tests w/ code coverage
       run: xcodebuild test -scheme CryptoScraper-Package -destination platform="macOS" -enableCodeCoverage YES

     - name: Upload coverage reports to Codecov
       uses: codecov/codecov-action@v3